# Generated by Django 4.1.7 on 2023-05-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscategory',
            old_name='user',
            new_name='users',
        ),
    ]
