# Generated by Django 4.1.7 on 2023-05-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_subscategory_users_subscategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubsCategory',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
