# Generated by Django 4.1.7 on 2023-05-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_subscategory_author_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='SubsCategory',
        ),
    ]
